### ISSUE TITLE
Si el entrenamiento no tiene ejercicio falla al obtener el primer elemento, tendría que poder ser nulo

### ISSUE THREAD

**Issue by emolinautn** [facupepi/TPCOMPLEMENTARIO2#2]
https://github.com/facupepi/TPCOMPLEMENTARIO2/blob/852316d6c7c75285ed3d5c8f59f7f6fc7891d4b7/src/main/kotlin/Entrenamiento.kt#L17

**Comment by facupepi** [comment]
Ahi lo corregi profe, puse que el metodo puede devolver null o ejercicio, y me asegure con el if que, si el entrenamiento tiene ejercicios, si o si entre la primera vez porque se cumple if (ejercicioMayor == null). Si no hay ejercicios, nunca entra al for ni al if, entonces devuelve null.

Asi estaria bien?

**Comment by facupepi** [comment]
ahi hice un commit del cambio

**Comment by emolinautn** [comment]
Ahora si esta perfecto muy bueno como lo resolviste no se me hubiera ocurrido, hay un metodo de la lista que es firstOrNull, pero esta bien dejalo así.

**Comment by facupepi** [comment]
gracias Ema
